pipeline {
    agent any

    stages {
        stage('Verify Django Project') {
            steps {
                sh '''
                    cd backend
                    python3 manage.py check
                '''
            }
        }
    }
}