# Generated by Django 6.0.7 on 2026-07-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_branch',
            field=models.CharField(default='main', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='technology',
            field=models.CharField(choices=[('Python Django', 'Python Django'), ('Python Flask', 'Python Flask'), ('Java Spring Boot', 'Java Spring Boot'), ('Node.js', 'Node.js'), ('React', 'React'), ('Angular', 'Angular'), ('Docker', 'Docker'), ('Other', 'Other')], default='Python Django', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=20),
        ),
    ]
