# Generated by Django 6.0.7 on 2026-08-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_default_branch_project_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='jenkins_job',
            field=models.CharField(blank=True, help_text='Jenkins Pipeline Job Name', max_length=200),
        ),
    ]
