# Generated by Django 6.0.7 on 2026-08-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_jenkins_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='jenkins_job',
        ),
    ]
