# Generated by Django 6.0.7 on 2026-07-16 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('commit_hash', models.CharField(max_length=100)),
                ('console_log', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='pipeline.pipeline')),
            ],
        ),
    ]
