# Generated by Django 6.0.7 on 2026-07-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='console_log',
            field=models.TextField(blank=True),
        ),
    ]
