# Generated by Django 6.0.7 on 2026-07-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_build_console_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
