# Generated by Django 6.0.7 on 2026-07-27 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_build_ai_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='build',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='build',
            name='project_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='build',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
