# Generated by Django 6.0.7 on 2026-07-27 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_build_owner_alter_build_ai_summary_and_more'),
        ('pipeline', '0002_pipeline_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='pipeline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='pipeline.pipeline'),
            preserve_default=False,
        ),
    ]
