# Generated by Django 6.0.7 on 2026-08-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_build_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='build',
            name='console_log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
