# Generated by Django 6.0.7 on 2026-07-27 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_pipeline_owner'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='projects.project'),
            preserve_default=False,
        ),
    ]
